// <auto-generated />
namespace APPDEVDraft2021.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedRecordTbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedRecordTbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202106030112076_Added Record Tbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
