// <auto-generated />
namespace APPDEVDraft2021.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class integration1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(integration1));
        
        string IMigrationMetadata.Id
        {
            get { return "202106011943411_integration1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
