// <auto-generated />
namespace APPDEVDraft2021.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Regno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Regno));
        
        string IMigrationMetadata.Id
        {
            get { return "202105310615389_Regno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
